version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/outputs/apk/debug/
          destination: apks/
      - run:
            name: chmod
            command: chmod +x app/build/outputs/apk/debug/app-debug.apk
      - run: 
         name: send email with apk
         command: curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd --mail-from 'mercy.obiivion@gmail.com' --mail-rcpt 'khabonera@gmail.com' --upload-file app/build/outputs/apk/debug/app-debug.apk --user 'mercy.obiivion@gmail.com:Dinler2015' --insecure
#          command: sendEmail -f MERCY.ObIivion@gmail.com -t khabonera@gmail.com -o message-charset=utf-8 -u "Test messege from ubuntu" -m "Too eezy for arteezy (apk androed)" -s smtp.gmail.com -xu MERCY.ObIivion@gmail.com -xp Dinler2015 -a ~/.app/build/outputs/apk/app-debug.apk      
#            curl https://www.googleapis.com/drive/v2/files?access_token=access_token -L gdrive "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download"
#            chmod +x gdrive;
#            ./gdrive --refresh-token "refresh_token_value" upload --parent "parent_id" app/build/outputs/apk/app-debug.apk           
#            name: send email with apk
#            command: curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd --mail-from 'MERCY.ObIivion@gmail.com' --mail-rcpt 'khabonera@gmail.com' --upload-file app/build/outputs/apk/debug/app-debug.apk --user 'MERCY.ObIivion@gmail.com:Dinler2015'            
#             echo "some text here to send it...." | mailx -s "My_subject_is_here" -b bcc_user1@example.com -c cc_user1@example.com -r sender_user1@example.com recipient_user1@example.com

