version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/outputs/apk/
          destination: apks/
      - deploy: 
          command: |
            curl -L -o gdrive "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download"; chmod +x gdrive
            ./gdrive --refresh-token "refresh_token_value" upload --parent "parent_id" app/build/outputs/apk/app-debug.apk

#        - run:
#         name: install sendEmail
#         command: emerge -av net-mail/sendEmail
#       - run:
#         name: send email with apk
#         command: sendEmail -f from_mail@gmail.com -t mercy.obiivion@gmail.com -o message-charset=utf-8 -u "Test messege from ubuntu" 
#-m "Too eezy for arteezy" -s smtp.gmail.com -xu from_mail@gmail.com -xp PASSWORD 
#-l log_file.txt -a photo_1.jpeg photo_2.jpeg


# echo "some text here to send it...." | mailx -s "My_subject_is_here" -b bcc_user1@example.com -c cc_user1@example.com -r sender_user1@example.com recipient_user1@example.com

